### PR TITLE
Add photo to users

### PR DESCRIPTION
**Pull request by cdrmr18**
@10035 @rbalendra @DraganGasic 

Added photos to user and added display on reviews
Screen Shot 2021-02-11 at 12 15 48 PM

### CODE REVIEW

**Comment by cdrmr18** [comment]
@10035 Updated pull to add a quick regex to get username from user email!
Screen Shot 2021-02-11 at 12 22 04 PM

**Comment by 10035** [comment]
Hey @cdrmr18 this is breaking on my local for some reason. Are you able to check this asap please? screenshot of error attached. 

Screen Shot 2021-02-13 at 11 48 02 am

**Review by 10035 — CHANGES_REQUESTED** [review]
For some reason the code is breaking on my local. Attached screenshot of error

Screen Shot 2021-02-13 at 11 48 02 am

**Review by 10035 — APPROVED** [review]
Sweet - let's name the little robot

**Pull request merged**
